[package]
name = "rs-size"
version = "0.1.0"
authors = ["insomnimus <insomnimus19@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
walkdir = "2"
pretty-bytes= "0.2.2"
itertools = "0.10.0"
glob = "0.3.0"
