[package]
name = "sz"
version = "0.4.0"
authors = ["insomnimus <insomnimus19@gmail.com>"]
edition = "2018"

[[bin]]
name = "sz"
path = "src/main.rs"

[dependencies]
walkdir = "2"
pretty-bytes= "0.2.2"
glob = "0.3.0"
clap = "3.0.0-beta.2"
