[package]
name = "sz"
version = "0.6.3"
authors = ["insomnimus <insomnimus19@gmail.com>"]
edition = "2018"

[dependencies]
clap = { version = "3.0.13", features = ["derive"] }
ignore = "0.4.18"
rayon = "1.5.1"

[target.'cfg(windows)'.dependencies]
globset = "0.4.8"
