[package]
name = "sz"
version = "0.6.0"
authors = ["insomnimus <insomnimus19@gmail.com>"]
edition = "2018"

[[bin]]
name = "sz"
path = "src/main.rs"

[dependencies]
clap = "3.0.0-beta.5"
ignore = "0.4.18"
rayon = "1.5.1"

[target.'cfg(windows)'.dependencies]
globset = "0.4.8"
